# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONbCec7wSLQfULu63FPfFx5gxG6nv-U1
"""

def show_levels():
  print("Welcome to the Guessing Game")
  print('''Choose your level:
  (1) Easy:
      * Limits : [1 - 10]
      * No. of trials : 5
  (2) Medium :
      * Limits : [1 - 100]
      * No. of trials : 10
  (3) Hard :
      * Limits : [1 - 1000]
      * No. of trials : 20 ''')
def game_level_choice():
  while True:
      game_level = input('Enter the game level :\n (1) Easy \t (2)  Medium  \t (3) Hard \t')
      if game_level in ['1','2','3']:
          game_level = int(game_level)
          break
      else:
          print('Invalid Choice! Please choose 1, 2, or 3')
          continue
  return game_level

def set_game_settings(game_level):
  if game_level == 1:
    limits = range(1,11)
    n_trials = 5
  elif game_level == 2:
    limits = range(1,101)
    n_trials = 10
  else:
    limits = range(1,1001)
    n_trials = 20
  return limits, n_trials
import random
def start_play(limits, n_trials):
  hidden = random.choice(limits)
  user_trials = 0

  while user_trials < n_trials:
    guess = int(input('Enter Your Guess: '))
    user_trials +=1

    if guess == hidden:
      print(f'You got it successfully in {user_trials} trials')
      break
    else:
      if user_trials == n_trials:
        print(f"Unfortunately, You tried {user_trials} trials. No more Trials!")
        print(f'The hidden number is  {hidden}')
      elif guess < hidden:
        print('No, Increase!')
      else:
        print('No, Decrease!')
    continue

def play_again():
  while True:
    play_again = (input('Do you want to play again? (y/n)')).strip().lower()
    if play_again not  in ['y']:
      print('Thanks for playing!')
      return False
    else:
      return True

def play():
  show_levels()
  while True:
    game_level = game_level_choice()
    limits, n_trials = set_game_settings(game_level)
    start_play(limits, n_trials)
    if not play_again():
        break

play()
play_again()